### ISSUE TITLE
The "id" argument must be of type string,  ReadableStream is not defined

### ISSUE THREAD

**Issue by mbykov** [scriptcoded/simple-pdf#1]
Something wrong:

yarn test 
....
==>    ReferenceError: ReadableStream is not defined
cd examples
node ./promises.js
....
==> Error: Setting up fake worker failed: "The "id" argument must be of type string. Received type object".

the same error with events.js

**Comment by scriptcoded** [comment]
Thank's for reporting!

I read through the readme, and realized that it's not clear how to run the examples and the tests. To run the tests you first need to build the library to generate the lib directory. This can be done with the command `npm run build`. The same goes for the examples. An easier way to run the examples might be `npm run example:promises`. If you look in `package.json` you'll see the available scripts.

As for why you're getting a `ReferenceError` when running the test suite is unclear to me. Could you perhaps provide a few details about your environment, such as operating system and Node.js version?

Worth noting is that I can't guarantee that this module can be run from source with Yarn, as I've developed it with NPM and only provide a `package-lock.json`.

I'll make sure to make the readme a bit more clear when I get the time.

**Comment by elliotsoomro** [comment]
I get the same error just from running the "minimal example". Help plz

**Comment by ddennis** [comment]
Same here

**Comment by scriptcoded** [comment]
A few people seem to be having this problem. I haven't had a lot of time to look in to it, but as a temporary workaround you can clone the project outside `node_modules`. The issue only seems to happen when the library is installed through NPM.

1. Clone the library into your project: `git clone git@github.com:scriptcoded/simple-pdf.git`
1. Enter the clone directory `cd simple-pdf`
1. Install dependencies `npm install`
1. Build the library `npm build`
1. Import the library using `const { SimplePDFParser } = require('./simple-pdf/lib')`

**Comment by scriptcoded** [comment]
There was an issue with PDF.js's alternate worker. This should be fixed with version v0.1.11.
